// create a user hakan
POST http://localhost:8080/auth/users
Content-Type: application/json

{
"credentials": { "username": "me@hakan.com",
"password": "Blah123!"
},
"extra": "hakan",
"friends": [{
"displayName": "steven",
"email": "steven@gmail.com"
}]
}

###

// create a user steven
POST http://localhost:8080/auth/users
Content-Type: application/json

{
"credentials": { "username": "steven@gmail.com",
"password": "Steven23!"
},
"extra": "steven"
}

###

// login for hakan with correct password
POST http://localhost:8080/auth/users/me@hakan.com
Content-Type: application/json

{
"password": "Blah123!"
}
###

// valid (for user hakan) and invalid tokens
@authTokenValid = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lQGhha2FuLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDB6R2dGUXBpN1JuN21aWXNxOXZ1eXVxYy4wQWM1VmszMXZTdlhZMjcwQzZybkxvM2dxazMuIiwiaWF0IjoxNzAxOTg2MjIyfQ.D1tNn37u9uOvR4Dz61CS_GneMugiyGNXa86N4NhI6GA
@authTokenInvalid = lol

###

// should fail since adding friend to himself
POST http://localhost:8080/friends/me@hakan.com
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
"displayName": "hakan",
"email": "me@hakan.com"
}

###

// should add friend but show needs invite
POST http://localhost:8080/friends/me@hakan.com
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
"displayName": "steven",
"email": "steven@gmail.com"
}

###

// should get friends for hakan
GET http://localhost:8080/friends/me@hakan.com
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

###

// should clear hakan friends
PATCH http://localhost:8080/friends/me@hakan.com
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

###

// should succeed because authenticated user is posting for self
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
"author": "me@hakan.com",
"text": "another strange post"
}

###

// get chat messages
GET http://localhost:8080/chat/messages
Authorization: Bearer {{authTokenValid}}


###

// login for hakan with incorrect password (fails)
POST http://localhost:8080/auth/users/me@hakan.com
Content-Type: application/json

{
"password": "incorrect"
}

###

// get users with invalid token (fails)
GET http://localhost:8080/chat/users/
Content-Type: application/json
Authorization: Bearer {{authTokenInvalid}}

###

// get users with valid token
GET http://localhost:8080/chat/users/
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

###

// login for hakan with no password (fails)
POST http://localhost:8080/auth/users/hakan@me.com
Content-Type: application/json

###

// get users with no token (fails)
GET http://localhost:8080/chat/users/
Content-Type: application/json

###

// should fail because user is not the author of the post
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
"author": "me@serra.com",
"text": "some strange post"
}

####

// should fail because user doesn't exist
POST http://localhost:8080/chat/messages
Content-Type: application/json
Authorization: Bearer {{authTokenValid}}

{
"author": "someuser@blah.com",
"text": "some strange post"
}

###

/// should succeed because authorized user hakan can access his own info
GET http://localhost:8080/chat/users/me@hakan.com
Authorization: Bearer {{authTokenValid}}

###

/// should not succeed, because user is getting info on another user)
GET http://localhost:8080/chat/users/me@serra.com
Authorization: Bearer {{authTokenValid}}